### ISSUE TITLE
Manpage를 위한 Roxygen tag 오류

### ISSUE THREAD

**Issue by choonghyunryu** [tidyverse-korea/statdata#22]
패키지를 빌드한 후 리눅스, MS-Windows에서 한글 이슈를 해결하는 과정에서
Manpage를 위한 Roxygen tag 오류를 발견하고, fix하는 방법을 공유합니다.

아마도 전 건 수정이 필요해 보입니다.

**앞으로 작성할 것만 아래 방식대로 수정해 주시고, 기존의 것은 건들지 말아 주세요. 한 사람이 모아서 수정하는 것이 바람직할 것 같아요. 늦게 발견할 원죄로, 제가 일괄 수정하겠습니다.**

1. 수정 내역 1
    - @return \item{jinwook_unit_score}{데이터프레임}이 불필요하게 들어가 있습니다.
    - @return는 함수의 리런 값을 설명하는 태그입니다. 그러므로 데이터 도움말에는 사용하지 않습니다.
        - **삭제해야 합니다.**
1. 수정내역 2
    - \describe{}의 위치가 잘못되었음 
    - \describe{}의 위치는 @format 다음에 와야 합니다. 이것은 format을 구체적으로 설명하는 태그입니다. 
        - **위치를 바꾸어야 합니다.**    

**다음은 jinwook_unit_score : 초등수학 5-2 데이터에 대한 도움말을 생성하기 위한 Roxygen 문법의 태그입니다.**

#' jinwook_unit_score : 초등수학 5-2
#'
#' 초등수학 5-2 교과서에 수록된 진욱이의 단원평가 점수 데이터
#'
#'
#' @format 변수 2개와 5행을 갖는 티블 데이터프레임:
#' @aliases 진욱이의 단원평가 점수
#' @docType data
#' @return \item{jinwook_unit_score}{데이터프레임}
#' \describe{
#'   \item{\code{단원}}{character 1단원부터 5단원까지}
#'   \item{\code{점수}}{double 진욱이의 단원평가 점수, 단위: 점}
#'}
#' @details  초등수학 5-2 교과서에 수록된 1단원부터 5단원까지 각 단원에 대한 진욱이의 단원평가 점수 데이터
#' @source \url{http://estat.me/estat/eStat/}
#' @keywords datasets
"jinwook_unit_score"

**이것을 수정하면 다음과 같습니다.**

#' jinwook_unit_score : 초등수학 5-2
#'
#' 초등수학 5-2 교과서에 수록된 진욱이의 단원평가 점수 데이터
#'
#'
#' @format 변수 2개와 5행을 갖는 티블 데이터프레임:
#' \describe{
#'   \item{\code{단원}}{character 1단원부터 5단원까지}
#'   \item{\code{점수}}{double 진욱이의 단원평가 점수, 단위: 점}
#'}
#' @aliases 진욱이의 단원평가 점수
#' @docType data
#' @details  초등수학 5-2 교과서에 수록된 1단원부터 5단원까지 각 단원에 대한 진욱이의 단원평가 점수 데이터
#' @source \url{http://estat.me/estat/eStat/}
#' @keywords datasets
"jinwook_unit_score"

**Comment by HwayoungYoon** [comment]
**add eStat data #14** PR에 포함되는 data에 대한 Roxygen tag 오류 수정했습니다.

**Comment by choonghyunryu** [comment]
@HwayoungYoon 
일단 제가 다 수정했습니다. 
그리고 수정본을 Pull Request했습니다.

**앞으로 작성할 것만 아래 방식대로 수정해 주시고, 기존의 것은 건들지 말아 주세요.**
